/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gopro.desktop;

import com.gopro.entity.*;
import com.gopro.model.*;
import java.util.*;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.*;

/**
 *
 * @author jgomez
 */
public class ContactoJframe extends javax.swing.JFrame {

    private final ContactoModel contactoModel = new ContactoModel();
    
    private final PaisModel paisModel = new PaisModel();
    
    private final TreeMap <Long, String> paisMap = new TreeMap<>();
    
    DefaultTableModel dtm = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int row, int column)
        {
            if(column == 0){
                return false;
            }else{
                return true;
            }
        }
        

        @Override
        public void setValueAt(Object value, int row, int col) {
            
            super.setValueAt(value,row,col);
            
            fireTableCellUpdated(row, col);
            
            Long llave = (Long) dtm.getValueAt(row, 0);
            
            String valor1 = (String) dtm.getValueAt(row, 1);
            
            String valor2 = (String) dtm.getValueAt(row, 2);
            
            if(!"".equals((String) valor1) && !"".equals(valor2)){
                if(llave != null){
                    Contacto contacto = contactoModel.find(llave);
                    contacto.setNombre((String) valor1);
                    contacto.setPais(paisModel.find(getKeyForValue((String) valor2)));
                    contactoModel.update(contacto);
                }else{
                    Contacto contacto = new Contacto();
                    contacto.setNombre((String) valor1);
                    contacto.setPais(paisModel.find(getKeyForValue((String) valor2)));
                    contactoModel.create(contacto);
                }
            }
        }
    };

    private final List<Long> removedRows = new ArrayList<>();

    
    
    /**
     * Creates new form Pais
     */
    public ContactoJframe() {
        initComponents();
        LlenarTabla();
    }
    
    private Long getKeyForValue(String value) {
        for (Map.Entry<Long, String> entry : paisMap.entrySet()) {
             if (entry.getValue().equals(value)) {
                 return entry.getKey();
             }
         }
        return new Long(0);
    }
    
    private void LlenarTabla(){
        
        for (Pais pais : this.paisModel.findAll()){
            paisMap.put(pais.getId(), pais.getNombre());
        }
        
        dtm.addColumn("Id");
        dtm.addColumn("Nombre");
        dtm.addColumn("Pais");
        
        
        for (Contacto contacto : this.contactoModel.findAll()){
            dtm.addRow(new Object[]{contacto.getId(), contacto.getNombre(), contacto.getPais().getNombre()});
        }
        
        this.paisTabla.setModel(dtm);
        
        TableColumn idColumn = paisTabla.getColumnModel().getColumn(0);
        TableColumn paisColumn = paisTabla.getColumnModel().getColumn(2);

        
        JComboBox comboBox = new JComboBox();
        
        for (Pais pais : this.paisModel.findAll()){
            comboBox.addItem(pais.getNombre());
        }
        idColumn.setPreferredWidth(10);
        paisColumn.setCellEditor(new DefaultCellEditor(comboBox));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paisTabla = new javax.swing.JTable();
        AgregarBoton = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paisTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        paisTabla.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(paisTabla);

        AgregarBoton.setText("Nuevo");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        BorrarBoton.setText("Borrar");
        BorrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AgregarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BorrarBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBoton)
                    .addComponent(BorrarBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        
        dtm.addRow(new Object[]{null, "", ""});

    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void BorrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBotonActionPerformed
        int[] rows = paisTabla.getSelectedRows();
        for(int i=0;i<rows.length;i++){
            Long valor = (Long)dtm.getValueAt(rows[i]-i, 0);
            if(valor != null){
                removedRows.add(valor);
                System.out.println(((Long) dtm.getValueAt(rows[i]-i, 0)));
            }
            dtm.removeRow(rows[i]-i);
        }
    }//GEN-LAST:event_BorrarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactoJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ContactoJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paisTabla;
    // End of variables declaration//GEN-END:variables
}
