/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gopro.desktop;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author jgomez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    
    private AutenticacionJdialog passDialog;

    public void TestFrame() {
        passDialog = new AutenticacionJdialog(this, true);
        passDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        SistemaMenu = new javax.swing.JMenu();
        SalirMenuItem1 = new javax.swing.JMenuItem();
        MantenimientoMenu = new javax.swing.JMenu();
        PaisMenuItem = new javax.swing.JMenuItem();
        EmpresaMenuItem = new javax.swing.JMenuItem();
        ClienteMenuItem1 = new javax.swing.JMenuItem();
        ProveedorMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");

        SistemaMenu.setText("Sistema");

        SalirMenuItem1.setText("Salir");
        SalirMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMenuItem1ActionPerformed(evt);
            }
        });
        SistemaMenu.add(SalirMenuItem1);

        jMenuBar1.add(SistemaMenu);

        MantenimientoMenu.setText("Mantenimiento");

        PaisMenuItem.setText("Paises");
        PaisMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisMenuItemActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(PaisMenuItem);

        EmpresaMenuItem.setText("Empresas");
        EmpresaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpresaMenuItemActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(EmpresaMenuItem);

        ClienteMenuItem1.setText("Clientes");
        ClienteMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteMenuItem1ActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(ClienteMenuItem1);

        ProveedorMenuItem.setText("Proveedores");
        ProveedorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorMenuItemActionPerformed(evt);
            }
        });
        MantenimientoMenu.add(ProveedorMenuItem);

        jMenuBar1.add(MantenimientoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaisMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisMenuItemActionPerformed
        PaisJframe pais = new PaisJframe();
        pais.setLocationRelativeTo(null);
        pais.setVisible(true);
    }//GEN-LAST:event_PaisMenuItemActionPerformed

    private void EmpresaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpresaMenuItemActionPerformed
        EmpresaJframe empresa = new EmpresaJframe();
        empresa.setLocationRelativeTo(null);
        empresa.setVisible(true);
        
    }//GEN-LAST:event_EmpresaMenuItemActionPerformed

    private void SalirMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirMenuItem1ActionPerformed

    private void ClienteMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteMenuItem1ActionPerformed
        ClienteJframe cliente = new ClienteJframe();
        cliente.setLocationRelativeTo(null);
        cliente.setVisible(true);
    }//GEN-LAST:event_ClienteMenuItem1ActionPerformed

    private void ProveedorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorMenuItemActionPerformed
        ProveedorJframe proveedor = new ProveedorJframe();
        proveedor.setLocationRelativeTo(null);
        proveedor.setVisible(true);
    }//GEN-LAST:event_ProveedorMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Principal principal = new Principal();
                principal.setLocationRelativeTo(null);
                AutenticacionJdialog passDialog = new AutenticacionJdialog(principal, true);
                passDialog.setVisible(true);
                principal.getContentPane().setBackground(Color.WHITE);
                principal.setTitle("Principal -  Autenticado");
                principal.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                //principal.setExtendedState(JFrame.MAXIMIZED_BOTH);

            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClienteMenuItem1;
    private javax.swing.JMenuItem EmpresaMenuItem;
    private javax.swing.JMenu MantenimientoMenu;
    private javax.swing.JMenuItem PaisMenuItem;
    private javax.swing.JMenuItem ProveedorMenuItem;
    private javax.swing.JMenuItem SalirMenuItem1;
    private javax.swing.JMenu SistemaMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
